repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
      - id: black
        args:
          - --quiet

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile
          - black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.csv,*.json,*.ambr"
          - --quiet-level=2
        exclude_types: [csv, json]
